image: node:22-alpine

stages:
    - install
    - build
    - deploy

install:
    stage: install
    script:
        - npm ci
    artifacts:
        paths:
            - node_modules/

build:
    stage: build
    script:
        - npm run build
    dependencies:
        - install
    artifacts:
        paths:
            - dist/

pages:
    stage: deploy
    only:
        - master
    script:
        - echo "Deploying to GitLab Pages"
    artifacts:
        paths:
            - dist/
    dependencies:
        - install
        - build
